[mypy]
strict_equality = True
disallow_untyped_calls = True
warn_unreachable = True

[mypy-bosdyn.*]
ignore_missing_imports = True

[mypy-dill.*]
ignore_missing_imports = True

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-google.protobuf.wrappers_pb2.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
